// Code generated by command: go run asm-AndInplaceAVX512.go -out andInplaceAVX512_amd64.s -stubs andInplaceAVX512.go. DO NOT EDIT.

//go:build amd64

package pand

func andInplaceAVX512(x []byte, y []byte)
