// Code generated by command: go run asm.go -out pand.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func PAND(x []byte, y []byte)
// Requires: AVX
TEXT ·PAND(SB), NOSPLIT|NOPTR, $0-48
	// pointer of x
	MOVQ x_base+0(FP), AX

	// length of x
	MOVQ x_len+8(FP), CX

	// pointer of y
	MOVQ y_base+24(FP), DX

	// --------------------------------------------
	// check number of left elements
	CMPQ CX, $0x00000008
	JL   tail
	CMPQ CX, $0x00000010
	JL   loop8
	CMPQ CX, $0x00000020
	JL   loop16

	// --------------------------------------------
loop32:
	// check number of left elements
	CMPQ CX, $0x00000020
	JL   loop16

	// compute x & y, and save value to x
	VMOVDQA (AX), Y0
	VANDPS  (DX), Y0, Y0
	VMOVDQA Y0, (AX)

	// move pointer
	ADDQ $0x00000020, AX
	ADDQ $0x00000020, DX
	SUBQ $0x00000020, CX
	JMP  loop32

	// --------------------------------------------
loop16:
	// check number of left elements
	CMPQ CX, $0x00000010
	JL   loop8

	// compute x & y, and save value to x
	VMOVDQA (AX), X0
	VANDPS  (DX), X0, X0
	VMOVDQA X0, (AX)

	// move pointer
	ADDQ $0x00000010, AX
	ADDQ $0x00000010, DX
	SUBQ $0x00000010, CX
	JMP  loop16

	// --------------------------------------------
loop8:
	// check number of left elements
	CMPQ CX, $0x00000008
	JL   tail

	// compute x & y, and save value to x
	MOVQ (AX), BX
	ANDQ (DX), BX
	MOVQ BX, (AX)

	// move pointer
	ADDQ $0x00000008, AX
	ADDQ $0x00000008, DX
	SUBQ $0x00000008, CX
	JMP  loop8

	// --------------------------------------------
tail:
	// left elements (<=8)
	MOVQ (AX), BX
	ANDQ (DX), BX
	MOVQ BX, (AX)
	RET
